### ISSUE TITLE
Error Notification has no styling

### ISSUE THREAD

**Issue by 7200rpm** [abevoelker/simple_form_tailwind#2]
For some reason my error notification shows up without any styling applied to it. 

Looked in the terminal and i'm getting some error about "undefined method `heroicon'"

Here's the gist of my code:

```
<%= simple_form_for ([:owner, @property,]), builder: SimpleForm::Tailwind::FormBuilder do |f| %>
  <%= f.error_notification  %>
```

**Comment by abevoelker** [comment]
That's odd, do you have the heroicon gem installed? Should've came in as part of the gem dependencies. https://github.com/bharget/heroicon

**Comment by 7200rpm** [comment]
So I added that gem separately and received an error on rails startup:

```
config/initializers/heroicon.rb:3:in `<main>': uninitialized constant Heroicon (NameError)
```

Wondering if I'm missing a step somewhere?

**Comment by abevoelker** [comment]
Ah I forgot about the setup that gem needs. That's an odd error regardless. I think I'll push out a version of the gem next week that doesn't require that dependency.

**Comment by 7200rpm** [comment]
that would be great. I opened an issue on the other gem. Thanks for all your work - this is super helpful!

**Comment by abevoelker** [comment]
Hey, I just realized you would probably get that error if you didn't add

```ruby
gem "heroicon"
```

to your Gemfile because my gem didn't have an explicit

```ruby
require "heroicon"
```

in it before. I just pushed out a change that I think will fix your issue if you do a

```
$ bundle update simple_form_tailwind
```

Let me know if that fixes your issue!

Also I realized I won't be able to factor out the use of the heroicon gem since I'm letting people use arbitrary icons with the `icon` option. So basically I'd have to reimplement the whole gem. So instead I fixed the instructions so people know about the gem dependency.

Thanks for reporting your issue and making the gem better for everyone!

**Comment by abevoelker** [comment]
@7200rpm FYI I've now published this as a gem on RubyGems as `simple_form_tailwind_css` (`simple_form_tailwind` was sadly already taken).

If you update your Gemfile to replace this line:

```ruby
gem "simple_form_tailwind", github: "abevoelker/simple_form_tailwind"
```

with this instead:

```
gem "simple_form_tailwind_css"
```

and do a

```
$ bundle
```

to update to the latest source I think your issue will be solved. Let me know if not!

**Comment by abevoelker** [comment]
Closing this for now - feel free to reopen if needed
